#!/usr/bin/env ruby
# frozen_string_literal: true

##
# Generate JSON for JIRA import.
# https://support.atlassian.com/jira-cloud-administration/docs/import-data-from-json/
#
# It generates everything, except bodies for issues & comments. We're going
# to update them via API later to be able to use Atlassian Document
# Format (= to make it nice).

require "sin"

repo_name = ENV.fetch("GITHUB_REPO_NAME")
data_dir = "data/#{repo_name}"

puts "Generating JSON for Jira..."
issues = Dir.glob("#{data_dir}/issues/*.json").map do |file|
  issue = JSON.parse(File.read(file))
  comments = JSON.parse(File.read(format("#{data_dir}/comments/%d.json", issue["number"])))
  Sin::Generator.new(ENV.fetch("JIRA_PROJECT_KEY"), issue, comments).to_jira
end

for_import = {
  projects: [
    {
      key: ENV.fetch("JIRA_PROJECT_KEY"),
      issues: issues
    }
  ]
}

File.write("#{data_dir}/jira-import-me.json", JSON.pretty_generate(for_import))
puts "- done, written to #{data_dir}/jira-import-me.json"
puts "- import at https://#{ENV.fetch("JIRA_HOST")}/secure/admin/JsonSetupPage!default.jspa?externalSystem=com.atlassian.jira.plugins.jim-plugin%3AjsonImporter"
